name: Build Debian Package For Docker Used In Termux

on:
  workflow_dispatch:
  
concurrency:
  group: build-termux-docker

jobs: 
  build-termux-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        platform: [arm, aarch64, i686, x86_64]
        package: [docker]

    steps:
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl gnupg
          sudo install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          sudo chmod a+r /etc/apt/keyrings/docker.gpg
          echo "deb [arch=\"$(dpkg --print-architecture)\" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo \"$VERSION_CODENAME\") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

      - name: Build Debian Package For Docker
        run: |
          cd $GITHUB_WORKSPACE
          git clone https://github.com/termux/termux-packages
          cd $(mktemp -q -d)
          rsync -a $GITHUB_WORKSPACE/termux-packages/ termux-packages
          cd termux-packages
          git reset --hard 21694ae13fc47b021262e1693ff76a559afd3930
          rm -rf $GITHUB_WORKSPACE/termux-packages/packages/golang
          mv packages/golang $GITHUB_WORKSPACE/termux-packages/packages/golang
          cd $GITHUB_WORKSPACE/termux-packages
          sed -i 's/local TERMUX_GO_VERSION=.*/local TERMUX_GO_VERSION=go1.20.5/' scripts/build/setup/termux_setup_golang.sh
          sed -i 's/local TERMUX_GO_SHA256=.*/local TERMUX_GO_SHA256=d7ec48cde0d3d2be2c69203bc3e0a44de8660b9c09a6e85c4732a3f7dc442612/' scripts/build/setup/termux_setup_golang.sh
          CONTAINER_NAME=${{ matrix.package }}-${{ matrix.platform }} scripts/run-docker.sh ./build-package.sh -I -a ${{ matrix.platform }} -o build --format debian ${{ matrix.package }}
          echo "deb_name=\"$(basename "$(cd build ./*\.deb | head -n 1)")\"" >> $GITHUB_ENV
          echo "deb_dir=\"$(dirname "$(cd build && pwd | head -n 1)")\"" >> $GITHUB_ENV

      - name: Upload Release
        uses: svenstaro/upload-release-action@v2
        with:
           repo_token: ${{ secrets.GITHUB_TOKEN }}
           file: ${{ env.deb_dir }}/${{ env.deb_name }}
           asset_name: ${{ env.deb_name }}
           tag: "${{ matrix.package }}-debian-package"
           release_name: "Debian Package For ${{ matrix.package }}"
           body: "test"
           overwrite: true
