name: Build Debian Package For Docker Used In Termux

on:
  workflow_dispatch:
  
concurrency:
  group: build-termux-docker

jobs: 
  build-termux-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        platform: [x86_64]

    steps:
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl gnupg
          sudo install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          sudo chmod a+r /etc/apt/keyrings/docker.gpg
          echo "deb [arch=\"$(dpkg --print-architecture)\" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo \"$VERSION_CODENAME\") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

      - name: Build Debian Package For Docker
        run: |
          git clone --depth=1 https://github.com/termux/termux-packages
          cd termux-packages
          sed -i 's/local TERMUX_GO_VERSION=.*/local TERMUX_GO_VERSION=go1.20.5/' ./scripts/build/setup/termux_setup_golang.sh
          sed -i 's/local TERMUX_GO_SHA256=.*/local TERMUX_GO_SHA256=d7ec48cde0d3d2be2c69203bc3e0a44de8660b9c09a6e85c4732a3f7dc442612/' ./scripts/build/setup/termux_setup_golang.sh
          CONTAINER_NAME=docker-${{ matrix.platform }} ./scripts/run-docker.sh ./build-package.sh -I -a aarch64 -o build --format debian docker
          ls build/*
          
