name: Build Kernel In Termux (Continuous)

on:
  workflow_dispatch:

concurrency:
  group: build-kernel-termux-continuous
  
env:
  KERNEL_REPO: "HunterXProgrammer/Termux-Docker-Kernel-Redmi-Xiaomi"
  KERNEL_REPO_BRANCH: "documentation"
  
jobs:
  prepare:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [x86_64]
      
    steps:
      - name: Set Build Architecture
        run: |
          if [ "${{ matrix.platform }}" = "i686" ]; then
            echo "arch_name=x86" >> $GITHUB_ENV
          else
            echo "arch_name=${{ matrix.platform }}" >> $GITHUB_ENV
          fi

      - name: Clone repository
        uses: actions/checkout@v4
        with:
          repository: "${{ env.KERNEL_REPO }}"
          ref: "${{ env.KERNEL_REPO_BRANCH }}"
          fetch-depth: 1

      - name: Build packages
        run: |
          mkdir -p build-deps
          mkdir -p build-status
          docker run --name kernel-builder-${{ matrix.platform }} termux/termux-docker:${{ matrix.platform }} bash -c "yes | pkg upgrade -y && pkg install -y git && git clone --depth=1 https://github.com/${{ env.KERNEL_REPO }} -b ${{ env.KERNEL_REPO_BRANCH }} ${{ env.KERNEL_REPO }} && cd ${{ env.KERNEL_REPO }} && export TERM=xterm-256color && timeout 1m bash build-termux.sh && echo true > kernel-continuous-build-finish || echo false > kernel-continuous-build-finish"
        
      - name: Generate build status and build deps
        run: |
          docker mv kernel-builder-${{ matrix.platform }}:/data/data/com.termux/files/home/${{ env.KERNEL_REPO }} ${{ env.KERNEL_REPO }}
          mv kernel-continuous-build-finish build-status
          zip -r9 build-deps/${{ env.arch_name }}-${{ env.KERNEL_REPO }}.zip ${{ env.KERNEL_REPO }}
    
      - name: Upload build deps
        uses: actions/upload-artifact@v3
        with:
          name: build-deps-${{ env.target_arch }}-${{ env.KERNEL_REPO }}
          path: ./build-deps
          
      - name: Upload build status
        uses: actions/upload-artifact@v3
        with:
          name: build-status-${{ env.archname }}-${{ env.KERNEL_REPO }}
          path: ./build-status

  build-1:
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        platform: [x86_64]
      
    steps:
      - name: Set Build Architecture
        run: |
          if [ "${{ matrix.platform }}" = "i686" ]; then
            echo "arch_name=x86" >> $GITHUB_ENV
          else
            echo "arch_name=${{ matrix.platform }}" >> $GITHUB_ENV
          fi
          
      - name: Download build deps
        uses: actions/download-artifact@v3
        with:
          name: build-deps-${{ env.arch_name }}-${{ env.KERNEL_REPO }}
          path: ./build-deps
          
      - name: Download build status
        uses: actions/download-artifact@v3
        with:
          name: build-status-${{ env.arch_name }}-${{ env.KERNEL_REPO }}
          path: ./build-status
          
      - name: Build packages
        run: |
          echo "$(cat ./build-status/kernel-continuous-build-finish)"
          if [ "$(cat ./build-status/kernel-continuous-build-finish)" = "true" ]; then
            exit 0
          fi
          unzip -o build-deps/${{ env.arch_name }}-${{ env.KERNEL_REPO }}.zip -d ./
          rm -rf build-deps/${{ env.arch_name }}-${{ env.KERNEL_REPO }}.zip
          ls -rla ${{ env.KERNEL_REPO }}
          docker run --name kernel-builder-${{ matrix.platform }} termux/termux-docker:${{ matrix.platform }} bash -c "yes | pkg upgrade -y && exit 0"
          docker mv ${{ env.KERNEL_REPO }} kernel-builder-${{ matrix.platform }}:/data/data/com.termux/files/home/${{ env.KERNEL_REPO }}
          docker run --name kernel-builder-${{ matrix.platform }} termux/termux-docker:${{ matrix.platform }} bash -c "cd ${{ env.KERNEL_REPO }} && export TERM=xterm-256color && timeout 1m bash build-termux.sh && echo true > kernel-continuous-build-finish || echo false > kernel-continuous-build-finish"
        
      - name: Generate build status and build deps
        run: |
          echo "$(cat ./build-status/kernel-continuous-build-finish)"
          docker mv kernel-builder-${{ matrix.platform }}:/data/data/com.termux/files/home/${{ env.KERNEL_REPO }} ${{ env.KERNEL_REPO }}
          mv kernel-continuous-build-finish build-status
          zip -r9 build-deps/${{ env.arch_name }}-${{ env.KERNEL_REPO }}.zip ${{ env.KERNEL_REPO }}

  finished-build:
    runs-on: ubuntu-latest
    needs: build-1
    strategy:
      fail-fast: false
      matrix:
        platform: [x86_64]
      
    steps:
      - name: Set Build Architecture
        run: |
          if [ "${{ matrix.platform }}" = "i686" ]; then
            echo "arch_name=x86" >> $GITHUB_ENV
          else
            echo "arch_name=${{ matrix.platform }}" >> $GITHUB_ENV
          fi
          
      - name: Download build deps
        uses: actions/download-artifact@v3
        with:
          name: build-deps-${{ env.arch_name }}-${{ env.KERNEL_REPO }}
          path: ./build-deps
          
      - name: Download build status
        uses: actions/download-artifact@v3
        with:
          name: build-status-${{ env.arch_name }}-${{ env.KERNEL_REPO }}
          path: ./build-status
          
      - name: Check build status
        run: |
          echo "$(cat ./build-status/kernel-continuous-build-finish)"
          
          if [ "$(cat ./build-status/kernel-continuous-build-finish)" = "true" ]; then
            echo "[ERROR]: Need more time to build!"
          exit 1
          fi
          
          echo "ZIPNAME=$(basename $(ls out/*\.zip | head -n 1))" >> $GITHUB_ENV

      - name: Upload Release
        uses: svenstaro/upload-release-action@v2
        with:
           repo_token: ${{ secrets.GITHUB_TOKEN }}
           file: kernel-repo/out/${{ env.ZIPNAME }}
           asset_name: "TermuxDockerCompatible-KernelRedmi-9-9S-Pro-ProMax-miatoll.zip"
           tag: "redmi-note-9"
           release_name: "Redmi Note 9/9S/Pro/Pro Max"
           body: "Termux Docker compatible kernel for Redmi Note 9/9S/Pro/Pro Max"
           overwrite: true
