name: CI Test
on:
  workflow_dispatch:
  
concurrency:
  group: ci-test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Space Before Cleanup
        run: |
          echo "Free space:"
          df -h
          
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'

          
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      
