name: CI Test
on:
  workflow_dispatch:
  
concurrency:
  group: ci-test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Pause
      run: |
          yes | sudo apt upgrade -y
          sleep 10
    - uses: actions/checkout@v3
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      
