name: kernel build
on:
  workflow_dispatch:
  
concurrency:
  group: ci2-test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Space Before Cleanup
        run: |
          echo "Free space:"
          df -h

      - name: Free additional disk space
        if: ${{ env.build_completed != 'true' }}
        run: |
          sudo apt purge -yq $(dpkg -l | grep '^ii' | awk '{ print $2 }' | grep -P '(cabal-|dotnet-|ghc-|libmono|php|aspnetcore)') mono-runtime-common monodoc-manual ruby &>/dev/null
          sudo apt autoremove -yq &>/dev/null
          sudo rm -rf /opt/hostedtoolcache /usr/local /usr/share/dotnet /usr/share/swift
          
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Setup Build
        run: |
          mkdir project
          export HOME=$(pwd)/project
          wget https://dl.google.com/android/repository/platform-tools-latest-linux.zip
          unzip platform-tools-latest-linux.zip -d ~
          export PATH="$HOME/platform-tools:$PATH"
          apt install -yq bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev lib32ncurses5-dev libncurses5 libncurses5-dev
          mkdir -p ~/bin
          mkdir -p ~/android/lineage
          curl -L https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          export PATH="$HOME/bin:$PATH"
          git config --global user.email "test@test.com"
          git config --global user.name "test"
          git lfs install
          # export USE_CCACHE=1
          export USE_CCACHE=0
          export CCACHE_EXEC=/usr/bin/ccache
          # ccache -M 50G
          cd ~/android/lineage
          yes | repo init -u https://github.com/LineageOS/android.git -b lineage-20.0 --git-lfs
          repo sync









      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
