name: TestBuild Debian Package For Docker Used In Termux

on:
  workflow_dispatch:
  
concurrency:
  group: build-termux-docker

jobs: 
  build-termux-docker:
    runs-on: macos-latest
    permissions:
      contents: write
    strategy:
      matrix:
        platform: [x86_64]

    steps:
      - name: Setup Docker on macOS
        uses: douglascamata/setup-docker-macos-action@v1-alpha

      - name: Set Build Architecture
        run: |
          if [ "${{ matrix.platform }}" = "aarch64" ]; then
            echo "arch_name=arm64" >> $GITHUB_ENV
          elif [ "${{ matrix.platform }}" = "i686" ]; then
            echo "arch_name=x86" >> $GITHUB_ENV
          else
            echo "arch_name=${{ matrix.platform }}" >> $GITHUB_ENV
          fi

      - name: Build Debian Package For Docker
        run: |
          mkdir -p build
          
          # Support for ARM and AARCH64
          if [[ "${{ matrix.platform }}" == "arm" || "${{ matrix.platform }}" == "aarch64" ]]; then
            docker pull aptman/qus
            # docker run --rm --privileged aptman/qus -s -- -p arm aarch64
          fi

          docker pull termux/termux-docker:${{ matrix.platform }}
          docker run --privileged --name kernel-builder-${{ matrix.platform }} termux/termux-docker:${{ matrix.platform }} bash -c "yes | pkg upgrade -y && pkg install -y git libandroid termux-exec tar && git clone --depth=1 https://github.com/HunterXProgrammer/Termux-Docker-Kernel-Redmi-Xiaomi -b documentation repo && cd repo && export TERM=xterm-256color && unset LD_PRELOAD && bash build-termux.sh"
          docker ls kernel-builder-${{ matrix.platform }}:/data/data/com.termux/files/home/repo/out
